### ISSUE TITLE
Tomography

### ISSUE THREAD

**Issue by joshcombes** [rigetti/forest-benchmarking#94]
+ [x] Ensure process tomography is using the superoperator utils (**done** https://github.com/rigetti/forest-benchmarking/pull/120)
+ [x] Remove the hacks https://github.com/rigetti/forest-benchmarking/issues/13 , i.e. all the shimming and the like (**done** https://github.com/rigetti/forest-benchmarking/pull/120)
+ [x] Tomography should default to Pauli eigenbasis preparation and measure. https://github.com/rigetti/forest-benchmarking/issues/85 (**done** https://github.com/rigetti/forest-benchmarking/pull/105 )
+ [x] Check definitions of gates and operators in test_state_tomography and Hinton https://github.com/rigetti/forest-benchmarking/issues/16 (**done** https://github.com/rigetti/forest-benchmarking/pull/103)
